#!/usr/bin/env python3
# mkdict.py: build a legacy identify blob for an intentproto firmware.
#
# Runs a compiled dictionary-dump binary (tools/dump_dict.cpp linked
# with the firmware's declaration translation units), validates the
# JSON it prints, zlib-compresses it at level 9 — the payload a
# legacy klippy host expects from the identify command — and writes:
#
#   OUTDIR/identify.json    the uncompressed dictionary, for humans
#   OUTDIR/identify_blob.h  a C array to assign to
#                           Config::identify_blob / identify_blob_len
#
# Dependency-free: Python 3 standard library only.
#
# Usage:
#   mkdict.py path/to/dump_dict [-o OUTDIR]
#             [--version V] [--build-version B]

import argparse
import json
import subprocess
import sys
import zlib
from pathlib import Path

HEADER_TEMPLATE = """\
/* Generated by intentproto tools/mkdict.py — do not edit.
 * zlib-compressed identify dictionary ({raw} bytes JSON -> {n} bytes).
 * Assign to intentproto::Config::identify_blob / identify_blob_len.
 */
#ifndef INTENTPROTO_IDENTIFY_BLOB_H
#define INTENTPROTO_IDENTIFY_BLOB_H

#include <stddef.h>
#include <stdint.h>

static const uint8_t identify_blob[{n}] = {{
{body}
}};
static const size_t identify_blob_len = sizeof(identify_blob);

#endif /* INTENTPROTO_IDENTIFY_BLOB_H */
"""


def c_array_body(blob, per_line=12):
    lines = []
    for i in range(0, len(blob), per_line):
        chunk = blob[i:i + per_line]
        lines.append("    " + ", ".join("0x%02x" % b for b in chunk) + ",")
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(
        description="Compress an intentproto dictionary into the "
                    "identify blob header")
    p.add_argument("binary",
                   help="compiled dictionary dump tool (dump_dict.cpp "
                        "linked with the firmware's declarations)")
    p.add_argument("-o", "--out-dir", default=".",
                   help="output directory (default: .)")
    p.add_argument("--version", default="intentproto-dev",
                   help="dictionary 'version' string")
    p.add_argument("--build-version", default="",
                   help="dictionary 'build_version' string")
    args = p.parse_args()

    cmd = [args.binary, args.version, args.build_version]
    try:
        out = subprocess.run(cmd, stdout=subprocess.PIPE, check=True)
    except (OSError, subprocess.CalledProcessError) as e:
        sys.exit("mkdict: running %s failed: %s" % (args.binary, e))
    raw = out.stdout.strip()

    try:
        parsed = json.loads(raw)
    except ValueError as e:
        sys.exit("mkdict: dump tool printed invalid JSON: %s" % e)
    for key in ("commands", "responses", "config", "enumerations",
                "version", "build_version"):
        if key not in parsed:
            sys.exit("mkdict: dictionary is missing %r" % key)

    blob = zlib.compress(raw, 9)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    json_path = out_dir / "identify.json"
    header_path = out_dir / "identify_blob.h"
    json_path.write_bytes(raw + b"\n")
    header_path.write_text(HEADER_TEMPLATE.format(
        raw=len(raw), n=len(blob), body=c_array_body(blob)))

    print("mkdict: %s (%d msgs), %d bytes JSON -> %d bytes blob" % (
        parsed["version"],
        len(parsed["commands"]) + len(parsed["responses"]),
        len(raw), len(blob)))
    print("mkdict: wrote %s and %s" % (json_path, header_path))


if __name__ == "__main__":
    main()
