# A7 protocol/ABI hash — derived from intentproto's spec-frozen core ids.
#
# The wire contract every board and the host must agree on is the set of
# spec-frozen core message ids in intentproto (core_ids.hpp).  Hashing
# that canonical allocation gives one stable "protocol hash" that is the
# single version authority: bake it into every image and the host, and a
# handshake mismatch means "not in lockstep" — deterministically, with no
# judgement call.  Because the ids are spec-frozen (not per-build), the
# hash changes only when the contract itself changes.
#
# Copyright (C) 2026  JR Lomas <lomas.jr@gmail.com>
# This file may be distributed under the terms of the GNU GPLv3 license.

import hashlib
import os
import re

# Repo-root-relative path to the canonical core id allocation.
DEFAULT_CORE_IDS = os.path.normpath(os.path.join(
    os.path.dirname(__file__), "..", "..",
    "lib", "intentproto", "include", "intentproto", "core_ids.hpp"))

_RE_MSGID = re.compile(
    r"constexpr\s+uint32_t\s+(MSGID_\w+)\s*=\s*"
    r"(0x[0-9A-Fa-f]+|\d+)\s*;")


def parse_core_ids(text: str) -> dict:
    """Extract {MSGID_NAME: value} from a core_ids.hpp-style header."""
    out = {}
    for name, val in _RE_MSGID.findall(text):
        out[name] = int(val, 0)
    return out


def protocol_hash(defs: dict) -> str:
    """A stable 64-bit hex hash over the (name, id) allocation.

    Canonicalized by sorting on name so declaration order never affects
    the hash; both the id and the name are hashed so neither a renamed
    nor a renumbered message can collide with the old contract.
    """
    canon = "\n".join("%s=%d" % (name, defs[name]) for name in sorted(defs))
    return hashlib.sha256(canon.encode("utf-8")).hexdigest()[:16]


def host_protocol_hash(path=None) -> str:
    """Compute the host's protocol hash from the intentproto header."""
    with open(path or DEFAULT_CORE_IDS) as fh:
        defs = parse_core_ids(fh.read())
    if not defs:
        raise ValueError("no MSGID_* constants found in %s"
                         % (path or DEFAULT_CORE_IDS))
    return protocol_hash(defs)


def abi_header(hash_hex: str) -> str:
    """Emit a C header baking the protocol hash into an image.

    A build step generates this so the firmware advertises the same hash
    the host computes (via DECL_CONSTANT_STR, read from the dictionary at
    handshake — the A7 lockstep check).  Kept tiny and heap-free.
    """
    return (
        "// Generated by atlas.fleet.abi — do not edit.\n"
        "// The protocol/ABI hash of the intentproto core contract this\n"
        "// image was built against (FD-0002 §5 fleet coherence).\n"
        "#ifndef __PROTOCOL_ABI_HASH_H\n"
        "#define __PROTOCOL_ABI_HASH_H\n"
        '#include "command.h"\n'
        'DECL_CONSTANT_STR("PROTOCOL_ABI_HASH", "%s");\n'
        "#endif\n" % hash_hex)
