#!/usr/bin/env python3
# Generate an Ed25519 signing keypair for signed firmware images
# (RFC 0001 doc 11, "Signed images") and, optionally, the embedded C
# public-key header the bootloader compiles in.
#
# This produced the committed DEV/TEST keypair in keys/. The REAL
# release key is generated the same way but its private half never
# leaves the owner's server and is NEVER committed — see keys/README.md.
#
#   ./scripts/gen_signing_key.py --out-dir keys --name helix_dev_signing
#       writes <name>.key (32-byte private seed, hex) and
#              <name>.pub (32-byte public key, hex)
#   ./scripts/gen_signing_key.py --pub keys/helix_dev_signing.pub \
#       --header keys/helix_pubkey.h
#       (re)generates the embedded C header from an existing .pub
#
# Signing/keygen use the same pure-Python Ed25519 as scripts/sign_image.py
# (ed25519_ref), so this runs with only the standard library. If the
# `cryptography` package is importable it is used instead (faster).
#
# --seed <hex> makes the keypair deterministic (used to commit a stable
# dev key); omit it for a random key.

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sign_image import ed25519_publickey  # noqa: E402


def gen_header(pub, var="helix_pubkey"):
    lines = []
    lines.append("#ifndef HELIX_PUBKEY_H")
    lines.append("#define HELIX_PUBKEY_H")
    lines.append("// GENERATED by scripts/gen_signing_key.py from a"
                 " keys/*.pub file.")
    lines.append("// The Ed25519 public key the bootloader verifies signed"
                 " images against")
    lines.append("// (RFC 0001 doc 11). Regenerate after rotating the key with")
    lines.append("// scripts/gen_signing_key.py --pub keys/<name>.pub"
                 " --header keys/helix_pubkey.h")
    lines.append("#include <stdint.h>")
    lines.append("static const uint8_t %s[32] = {" % var)
    for i in range(0, 32, 8):
        row = ", ".join("0x%02x" % b for b in pub[i:i + 8])
        lines.append("    %s," % row)
    lines.append("};")
    lines.append("#endif // HELIX_PUBKEY_H")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out-dir", help="directory to write <name>.key/.pub")
    ap.add_argument("--name", default="helix_dev_signing")
    ap.add_argument("--seed", help="32-byte private seed as hex (deterministic)")
    ap.add_argument("--pub", help="read an existing .pub instead of generating")
    ap.add_argument("--header", help="also write the embedded C pubkey header")
    ap.add_argument("--var", default="helix_pubkey",
                    help="C array name in the header")
    args = ap.parse_args()

    if args.pub:
        with open(args.pub) as f:
            pub = bytes.fromhex(f.read().split()[0])
    else:
        if args.seed:
            seed = bytes.fromhex(args.seed)
            if len(seed) != 32:
                raise SystemExit("--seed must be 32 bytes (64 hex chars)")
        else:
            seed = os.urandom(32)
        pub = ed25519_publickey(seed)
        if args.out_dir:
            os.makedirs(args.out_dir, exist_ok=True)
            kp = os.path.join(args.out_dir, args.name + ".key")
            pp = os.path.join(args.out_dir, args.name + ".pub")
            with open(kp, "w") as f:
                f.write(seed.hex() + "\n")
            with open(pp, "w") as f:
                f.write(pub.hex() + "\n")
            os.chmod(kp, 0o600)
            print("wrote %s (private seed) and %s (public key)" % (kp, pp))
        else:
            print("seed:", seed.hex())

    print("pubkey:", pub.hex())
    if args.header:
        with open(args.header, "w") as f:
            f.write(gen_header(pub, args.var))
        print("wrote", args.header)


if __name__ == "__main__":
    main()
