#!/usr/bin/env python3
"""Offline V1-versus-HELIX pulse comparison for real sliced G-code.

This runner copies a printer configuration into a temporary directory, feeds
the selected leading layers through Klippy's file-output mode twice, and
decodes the resulting MCU command streams.  The legacy run is expanded from
``queue_step`` records into individual edges.  The HELIX run is retained as
the exact rebases and polynomial segments consumed by the MCU; a subsequent
analysis pass can replay those segments through the firmware solver.

No serial device is opened and no live printer configuration is modified.
"""

import argparse
import bisect
import ctypes
import json
import math
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[1]
KLIPPY = ROOT / "klippy" / "klippy.py"

sys.path.insert(0, str(ROOT / "klippy"))
sys.path.insert(0, str(ROOT / "klippy" / "extras"))
sys.path.insert(0, str(ROOT / "test"))
import msgproto  # noqa: E402
import trajectory_queuing  # noqa: E402
import trajectory_v1_pulse_compare as pulse_solver  # noqa: E402


WRITE_SECTIONS = {
    "atlas_trace",
    "failure_recovery",
}
HELIX_AUX_SECTIONS = {
    "helix_status",
    "helix_self_test",
    "timesync",
    "trajectory_queuing",
}
HEADER_RE = re.compile(r"^\s*\[([^]]+)\]\s*(?:[#;].*)?$")
FIELD_RE = re.compile(
    r"([A-Za-z_][A-Za-z0-9_]*)=(-?(?:0x[0-9A-Fa-f]+|[0-9]+))\b")


def strip_sections(text, removed):
    output = []
    skipping = False
    for line in text.splitlines(keepends=True):
        match = HEADER_RE.match(line)
        if match:
            skipping = match.group(1).strip().lower() in removed
        if not skipping:
            output.append(line)
    return "".join(output)


def make_config(source, destination, legacy):
    text = source.read_text()
    removed = set(WRITE_SECTIONS)
    if legacy:
        removed.update(HELIX_AUX_SECTIONS)
    text = strip_sections(text, removed)
    if legacy:
        text = re.sub(
            r"(?mi)^\s*motion_protocol\s*:\s*trajectory\s*(?:[#;].*)?\n?",
            "",
            text,
        )
    destination.write_text(text)


def extract_layers(gcode_path, layer_count, speed_percent):
    lines = gcode_path.read_text(errors="replace").splitlines()
    start_macro = next(
        (index for index, line in enumerate(lines)
         if line.strip().lower().startswith("print_start ")),
        None,
    )
    if start_macro is None:
        raise ValueError("G-code has no PRINT_START marker")
    layer_markers = [
        index for index, line in enumerate(lines)
        if line.strip() == ";LAYER_CHANGE"
    ]
    if len(layer_markers) <= layer_count:
        raise ValueError(
            "G-code has only %d layer markers; need %d"
            % (len(layer_markers), layer_count + 1)
        )
    end = layer_markers[layer_count]
    body = lines[start_macro + 1:end]
    prologue = [
        "; Generated by helix_gcode_pulse_compare.py",
        "; Offline only: establish the known post-start-macro coordinate",
        "SET_KINEMATIC_POSITION X=60 Y=60 Z=0",
        "M220 S%.9g" % (speed_percent,),
    ]
    return "\n".join(prologue + body + ["M400", ""])


def run_klippy(python, config, gcode, output, log, main_dict, mcu_dicts):
    command = [
        str(python), str(KLIPPY), str(config),
        "-i", str(gcode), "-o", str(output),
        "-d", str(main_dict), "-l", str(log),
    ]
    for name, dictionary in sorted(mcu_dicts.items()):
        command.extend(["-d", "%s=%s" % (name, dictionary)])
    result = subprocess.run(
        command, cwd=ROOT, stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT, text=True,
    )
    if result.returncode:
        tail = ""
        if log.exists():
            tail = "\n".join(log.read_text(errors="replace").splitlines()[-80:])
        raise RuntimeError(
            "offline Klippy run failed (%d):\n%s\n%s"
            % (result.returncode, result.stdout, tail)
        )


def load_parser(dictionary):
    parser = msgproto.MessageParser()
    parser.process_identify(dictionary.read_bytes(), decompress=False)
    return parser


def decode_stream(path, dictionary):
    parser = load_parser(dictionary)
    data = path.read_bytes()
    commands = []
    offset = 0
    while offset < len(data):
        packet_len = parser.check_packet(data[offset:])
        if packet_len < 0:
            raise ValueError("invalid MCU packet at byte %d in %s" % (
                offset, path))
        if not packet_len:
            raise ValueError("truncated MCU packet at byte %d in %s" % (
                offset, path))
        packet = data[offset:offset + packet_len]
        commands.extend(parser.dump(packet)[1:])
        offset += packet_len
    return commands


def parse_fields(command):
    fields = {}
    for key, value in FIELD_RE.findall(command):
        fields[key] = int(value, 0)
    return command.split()[0], fields


def expand_legacy_pulses(commands, invert_dirs=None):
    invert_dirs = invert_dirs or {}
    states = {}
    pulses = {}
    for command in commands:
        name, fields = parse_fields(command)
        if name == "config_stepper":
            oid = fields["oid"]
            states[oid] = {"clock": 0, "wire_direction": 0}
            pulses[oid] = []
        elif name == "reset_step_clock":
            states[fields["oid"]]["clock"] = fields["clock"]
        elif name == "set_next_step_dir":
            states[fields["oid"]]["wire_direction"] = fields["dir"]
        elif name == "queue_step":
            state = states[fields["oid"]]
            interval = fields["interval"]
            add = fields["add"]
            for _ in range(fields["count"]):
                state["clock"] += interval
                step_direction = (
                    state["wire_direction"]
                    ^ int(bool(invert_dirs.get(fields["oid"], 0))))
                pulses[fields["oid"]].append(
                    (state["clock"], 1 if step_direction else -1))
                interval += add
    return pulses


def trajectory_streams(commands):
    streams = {}
    for command in commands:
        name, fields = parse_fields(command)
        if name == "config_traj_stepper":
            streams[fields["oid"]] = []
        elif name in (
                "trajectory_rebase", "traj_hold", "queue_traj_segment",
                "queue_traj_segment_cubic", "queue_traj_segment_quintic"):
            streams[fields["oid"]].append((name, fields))
    return streams


def trajectory_invert_dirs(commands):
    result = {}
    for command in commands:
        name, fields = parse_fields(command)
        if name == "config_traj_stepper":
            result[fields["oid"]] = fields["invert_dir"]
    return result


def signed_i64(value):
    value &= (1 << 64) - 1
    return value - (1 << 64) if value & (1 << 63) else value


def replay_trajectory(streams, solver, local_frequency, primary_frequency):
    all_pulses = {}
    for oid, stream in streams.items():
        pulses = []
        clock = None
        acc = None
        mcu_position = None
        prior_interval = ctypes.c_uint32(0)
        prior_direction = ctypes.c_int32(0)
        pulse_buffer = (ctypes.c_uint32 * 65536)()
        for name, fields in stream:
            if name == "trajectory_rebase":
                clock = int(round(
                    fields["clock"] * local_frequency / primary_frequency))
                acc = signed_i64(fields["pos"] << 32)
                mcu_position = fields["mcu_pos"]
                continue
            if clock is None or acc is None or mcu_position is None:
                raise ValueError("trajectory command precedes rebase for oid %d"
                                 % (oid,))
            if name == "traj_hold":
                clock += int(round(
                    fields["duration"] * local_frequency
                    / primary_frequency))
                # A zero-coefficient hold loads as the negative fallback
                # direction in the firmware and therefore clears the pulse
                # interval predictor before subsequent positive motion.
                if prior_direction.value != -1:
                    prior_interval.value = 0
                prior_direction.value = -1
                continue

            duration = fields["duration"]
            velocity = fields["velocity"]
            acceleration = fields["accel"]
            jerk = fields.get("jerk", 0)
            snap = fields.get("snap", 0)
            crackle = fields.get("crackle", 0)
            end_delta = trajectory_queuing.py_end_delta_ho(
                duration, velocity, acceleration, jerk, snap, crackle)
            if name == "queue_traj_segment_quintic":
                flags = fields["flags"] | trajectory_queuing.TSEG_POLY_QUINTIC
            elif name == "queue_traj_segment":
                flags = fields["flags"]
            else:
                raise ValueError("unsupported trajectory command %s"
                                 % (name,))
            mpos_value = ctypes.c_int32(mcu_position)
            count = solver.helix_test_expand_segment(
                flags, duration, velocity, acceleration, jerk, snap, crackle,
                signed_i64(acc), ctypes.byref(mpos_value),
                ctypes.byref(prior_interval), ctypes.byref(prior_direction),
                pulse_buffer, len(pulse_buffer))
            if count == -2:
                raise ValueError(
                    "MCU solver divergence for oid %d at clock %d, acc %d,"
                    " mpos %d, prior interval %d, direction %d: %s %s" %
                    (oid, clock, acc, mcu_position, prior_interval.value,
                     prior_direction.value, name, fields)
                    + " after %d crossings (reason %s)" %
                    (pulse_buffer[len(pulse_buffer) - 1],
                     solver.helix_test_last_shutdown().decode()))
            if count < 0:
                raise ValueError("segment pulse buffer exhausted for oid %d"
                                 % (oid,))
            pulses.extend(
                (clock + pulse_buffer[index], prior_direction.value)
                for index in range(count))
            mcu_position = mpos_value.value
            acc = signed_i64(acc + end_delta)
            clock += duration
        all_pulses[oid] = pulses
    return all_pulses


def command_summary(commands):
    counts = {}
    for command in commands:
        name = command.split()[0]
        counts[name] = counts.get(name, 0) + 1
    return counts


def load_clock(dictionary):
    data = json.loads(dictionary.read_text())
    return int(data["config"]["CLOCK_FREQ"])


def pulse_summary(pulses, frequency):
    result = {}
    for oid, edges in pulses.items():
        intervals = [
            (edges[index][0] - edges[index - 1][0]) & 0xffffffff
            for index in range(1, len(edges))
            if edges[index][1] == edges[index - 1][1]
        ]
        result[str(oid)] = {
            "pulses": len(edges),
            "min_interval_ticks": min(intervals) if intervals else None,
            # A tiny same-direction interval is the signature of a solver
            # catch-up burst.  Report it explicitly so a full-file replay
            # cannot hide one behind an otherwise plausible minimum rate.
            "intervals_at_or_below_64_ticks": sum(
                interval <= 64 for interval in intervals),
            "max_step_rate": (
                frequency / min(intervals) if intervals else None),
        }
    return result


def percentile(values, fraction):
    if not values:
        return None
    ordered = sorted(values)
    position = int(math.ceil(fraction * len(ordered))) - 1
    return ordered[max(0, min(position, len(ordered) - 1))]


def compare_pulses(legacy, helix, frequency):
    comparison = {}
    for oid in sorted(set(legacy) | set(helix)):
        v1 = legacy.get(oid, [])
        hx = helix.get(oid, [])
        v1_by_direction = {
            direction: sorted(clock for clock, pulse_direction in v1
                              if pulse_direction == direction)
            for direction in (-1, 1)
        }
        signed_errors = []
        for clock, direction in hx:
            candidates = v1_by_direction[direction]
            if not candidates:
                continue
            index = bisect.bisect_left(candidates, clock)
            choices = candidates[max(0, index - 1):index + 1]
            nearest = min(choices, key=lambda candidate: abs(candidate - clock))
            signed_errors.append((clock - nearest) / frequency * 1.e6)
        errors = list(map(abs, signed_errors))
        comparison[str(oid)] = {
            "v1_pulses": len(v1),
            "helix_pulses": len(hx),
            "pulse_count_delta": len(hx) - len(v1),
            "nearest_directional_edges": len(errors),
            "edges_over_1ms": sum(error > 1000. for error in errors),
            "mean_abs_error_us": (
                sum(errors) / len(errors) if errors else None),
            "p95_abs_error_us": percentile(errors, .95),
            "p99_abs_error_us": percentile(errors, .99),
            "max_abs_error_us": max(errors) if errors else None,
            "min_signed_error_us": min(signed_errors)
            if signed_errors else None,
            "max_signed_error_us": max(signed_errors)
            if signed_errors else None,
        }
    return comparison


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("gcode", type=Path)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--main-dict", type=Path, required=True)
    parser.add_argument(
        "--mcu-dict", action="append", default=[], metavar="NAME=PATH")
    parser.add_argument("--python", type=Path,
                        default=Path(sys.executable))
    parser.add_argument("--layers", type=int, default=1)
    parser.add_argument("--speed-percent", type=float, default=25.)
    parser.add_argument("--keep", type=Path,
                        help="keep generated inputs and MCU streams here")
    args = parser.parse_args()

    if args.layers < 1:
        parser.error("--layers must be positive")
    mcu_dicts = {}
    for item in args.mcu_dict:
        if "=" not in item:
            parser.error("--mcu-dict must be NAME=PATH")
        name, path = item.split("=", 1)
        mcu_dicts[name] = Path(path)

    if args.keep:
        workdir = args.keep.resolve()
        workdir.mkdir(parents=True, exist_ok=True)
        cleanup = None
    else:
        cleanup = tempfile.TemporaryDirectory(prefix="helix-gcode-diff-")
        workdir = Path(cleanup.name)

    shutil.copy2(args.config.parent / "mainsail.cfg", workdir / "mainsail.cfg")
    legacy_config = workdir / "printer-v1.cfg"
    helix_config = workdir / "printer-helix.cfg"
    make_config(args.config, legacy_config, legacy=True)
    make_config(args.config, helix_config, legacy=False)
    input_gcode = workdir / "selected-layers.gcode"
    input_gcode.write_text(extract_layers(
        args.gcode, args.layers, args.speed_percent))

    solver = pulse_solver.build_mcu_solver()
    runs = {}
    captured_pulses = {"v1": {}, "helix": {}}
    invert_dirs = {}
    for mode, config in (("helix", helix_config), ("v1", legacy_config)):
        output = workdir / (mode + ".mcu")
        log = workdir / (mode + ".log")
        run_klippy(args.python, config, input_gcode, output, log,
                   args.main_dict, mcu_dicts)
        per_mcu = {"mcu": (output, args.main_dict)}
        per_mcu.update({
            name: (Path(str(output) + "-" + name), dictionary)
            for name, dictionary in mcu_dicts.items()
        })
        decoded = {}
        for name, (stream_path, dictionary) in per_mcu.items():
            commands = decode_stream(stream_path, dictionary)
            item = {"commands": command_summary(commands)}
            if mode == "v1":
                pulses = expand_legacy_pulses(
                    commands, invert_dirs.get(name, {}))
                captured_pulses[mode][name] = pulses
                item["steppers"] = pulse_summary(
                    pulses, load_clock(dictionary))
            else:
                streams = trajectory_streams(commands)
                invert_dirs[name] = trajectory_invert_dirs(commands)
                pulses = replay_trajectory(
                    streams, solver, load_clock(dictionary),
                    load_clock(args.main_dict))
                captured_pulses[mode][name] = pulses
                item["steppers"] = {
                    str(oid): {
                        "rebases": sum(c[0] == "trajectory_rebase"
                                       for c in stream),
                        "segments": sum(c[0].startswith("queue_traj_segment")
                                        for c in stream),
                        "holds": sum(c[0] == "traj_hold" for c in stream),
                        **pulse_summary(
                            {oid: pulses.get(oid, [])},
                            load_clock(dictionary))[str(oid)],
                    }
                    for oid, stream in streams.items()
                }
            decoded[name] = item
        runs[mode] = decoded

    comparison = {}
    dictionaries = {"mcu": args.main_dict, **mcu_dicts}
    for name, dictionary in dictionaries.items():
        comparison[name] = compare_pulses(
            captured_pulses["v1"].get(name, {}),
            captured_pulses["helix"].get(name, {}),
            load_clock(dictionary))

    report = {
        "source": str(args.gcode.resolve()),
        "layers": args.layers,
        "speed_percent": args.speed_percent,
        "workdir": str(workdir),
        "runs": runs,
        "comparison": comparison,
    }
    print(json.dumps(report, indent=2, sort_keys=True))
    if cleanup is not None:
        cleanup.cleanup()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
